package org.jenkinsci.plugins.vsphere.tools;

import edu.umd.cs.findbugs.annotations.CheckForNull;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Knows which Ethernet address ranges vSphere reserves for what, so that an address that vCenter is going to
 * refuse can be flagged up front and explained (JENKINS-34001).
 */
public final class MacAddresses {

    /** Where an address falls, as far as vSphere's allocation scheme is concerned. */
    public enum Kind {
        /** Not six hexadecimal bytes separated by ':' or '-'. */
        MALFORMED,
        /** 00:50:56:80:00:00 - 00:50:56:BF:FF:FF, which vCenter hands out itself ("VPX-assigned"). */
        VMWARE_VPX_GENERATED,
        /** 00:50:56:00:00:00 - 00:50:56:3F:FF:FF, the VMware block that may be set manually. */
        VMWARE_MANUAL,
        /** Elsewhere in 00:50:56, which vSphere does not accept for manual addresses. */
        VMWARE_RESERVED,
        /** 00:0C:29, generated by a standalone ESXi host. */
        HOST_GENERATED,
        /** Any other vendor's address block. */
        OTHER
    }

    private static final Pattern MAC = Pattern.compile("^([0-9A-Fa-f]{2})([:-][0-9A-Fa-f]{2}){5}$");

    private MacAddresses() {}

    public static Kind classify(@CheckForNull String address) {
        if (address == null) {
            return Kind.MALFORMED;
        }
        final String trimmed = address.trim();
        final Matcher m = MAC.matcher(trimmed);
        if (!m.matches()) {
            return Kind.MALFORMED;
        }
        final String[] bytes = trimmed.split("[:-]");
        final int b0 = Integer.parseInt(bytes[0], 16);
        final int b1 = Integer.parseInt(bytes[1], 16);
        final int b2 = Integer.parseInt(bytes[2], 16);
        final int b3 = Integer.parseInt(bytes[3], 16);
        if (b0 == 0x00 && b1 == 0x50 && b2 == 0x56) {
            if (b3 <= 0x3F) {
                return Kind.VMWARE_MANUAL;
            }
            if (b3 >= 0x80 && b3 <= 0xBF) {
                return Kind.VMWARE_VPX_GENERATED;
            }
            return Kind.VMWARE_RESERVED;
        }
        if (b0 == 0x00 && b1 == 0x0C && b2 == 0x29) {
            return Kind.HOST_GENERATED;
        }
        return Kind.OTHER;
    }
}
